### ISSUE TITLE
регістр

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/react-todo-app#1]
https://github.com/DenisPitsul/react-todo-app/blob/ca65156d76ba1a52008765c2397a802085373852/src/components/Loader/index.jsx#L1
- регістр в імені файлу інший, зараз через це помилка

**Comment by DenisPitsul** [comment]
Fixed in commit:
https://github.com/DenisPitsul/react-todo-app/commit/efd9fcd62f048d68739e334d684e7023d7a0ca4a
