### ISSUE TITLE
дати

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/react-todo-app#2]
https://github.com/DenisPitsul/react-todo-app/blob/ca65156d76ba1a52008765c2397a802085373852/src/utils/date.js#L1
- для перетворення дат зручно використовувати якусь бібліотеку, наприклад `date-fns`. Вона, наприклад, дає можливість легко додавати день, порівнювати дати, отримувати рядок з датою потрібного формату.

**Comment by DenisPitsul** [comment]
Refactored in commit:
https://github.com/DenisPitsul/react-todo-app/commit/efd9fcd62f048d68739e334d684e7023d7a0ca4a
