### ISSUE TITLE
деструктуризація

### ISSUE THREAD

**Issue by pecourses** [DenisPitsul/react-todo-app#3]
https://github.com/DenisPitsul/react-todo-app/blob/efd9fcd62f048d68739e334d684e7023d7a0ca4a/src/store/slices/userSlice.js#L21-L24
- тут красивіше було б деструктуризувати, хоча б до юзера, для уникнення таких довгих ланцюжків

**Comment by DenisPitsul** [comment]
Updated in commit:
https://github.com/DenisPitsul/react-todo-app/commit/0e7aafa10cf666938ee2d36b69ef0c5b0a48e0eb
